[CI] Bump cache version for pydeps
Due to recent CI changes, the former cache was messing with the build and
failing them at the browser testing step:
 - Making the venv relocatable failed silently for pytest scripts:
   "Script /home/circleci/repo/venv/bin/pytest cannot be made relative (it's
    not a normal script that starts with #!/home/circleci/repo/venv/bin/python)"
 - Which in turn made the test launch fail:
   ```
   Traceback (most recent call last):
     File "/tmp/ws/venv/bin/pytest", line 6, in <module>
       from pytest import main
   ModuleNotFoundError: No module named 'pytest'
   ```

This cache version change (and thus cache reset), according to CircleCI's
documentation is the right way to go to reset the cache, and was validated with
an intermediate version (1.001) to work.